package com.huatuo.pms.bo;

import java.io.Serializable;

@SuppressWarnings("serial")
public class BOOrgAndUser implements Serializable{
	private String username;
	private String realusername;
	private long userId;
	private int id;
	private int provinceCode;
	private String province;
	private int cityCode;
	private String city;
	private int countyCode;
	private String county;
	private int roadCode;
	private String road;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.parent_id
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private int parentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.name
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.alias_name
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String aliasName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.org_kind
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private int orgKind;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.org_district
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private long addressId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.address
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.setup_type
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private int setupType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.scale
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private int scale;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.telephone
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String telephone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.py_code
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String pyCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.email
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.description
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.d_code
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private String dCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.del_flag
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private boolean delFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_zd_org.is_open
	 * 
	 * @mbggenerated Thu Aug 06 14:28:37 CST 2015
	 */
	private boolean isOpen;

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getParentId() {
		return parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAliasName() {
		return aliasName;
	}

	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	public int getOrgKind() {
		return orgKind;
	}

	public void setOrgKind(int orgKind) {
		this.orgKind = orgKind;
	}

	public long getAddressId() {
		return addressId;
	}

	public void setAddressId(long addressId) {
		this.addressId = addressId;
	}

	public String getRealusername() {
		return realusername;
	}

	public void setRealusername(String realusername) {
		this.realusername = realusername;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getSetupType() {
		return setupType;
	}

	public void setSetupType(int setupType) {
		this.setupType = setupType;
	}

	public int getScale() {
		return scale;
	}

	public void setScale(int scale) {
		this.scale = scale;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getPyCode() {
		return pyCode;
	}

	public void setPyCode(String pyCode) {
		this.pyCode = pyCode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getdCode() {
		return dCode;
	}

	public void setdCode(String dCode) {
		this.dCode = dCode;
	}

	public boolean isDelFlag() {
		return delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	public boolean isOpen() {
		return isOpen;
	}

	public void setOpen(boolean isOpen) {
		this.isOpen = isOpen;
	}

	public int getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(int provinceCode) {
		this.provinceCode = provinceCode;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public int getCityCode() {
		return cityCode;
	}

	public void setCityCode(int cityCode) {
		this.cityCode = cityCode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public int getCountyCode() {
		return countyCode;
	}

	public void setCountyCode(int countyCode) {
		this.countyCode = countyCode;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public int getRoadCode() {
		return roadCode;
	}

	public void setRoadCode(int roadCode) {
		this.roadCode = roadCode;
	}

	public String getRoad() {
		return road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

}