package com.huatuo.pms.bo;

import java.io.Serializable;

@SuppressWarnings("serial")
public class BOPerson implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.user_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.name
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.age
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int age;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.sex
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.birthdate
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String birthdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.marry
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int marry;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.nation
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String nation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.birth_place
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String birthPlace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.province_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int provinceCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.province
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.city_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int cityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.city
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.county_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int countyCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.county
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String county;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.road_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int roadCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.road
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String road;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.home_district
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private long addressId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.home_address
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String homeAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.occupation_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int occupationId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.home_tel
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String homeTel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.social_id_type
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private int socialIdType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.social_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String socialId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.allergic_history
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private String allergicHistory;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.weight
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private double weight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_person.height
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	private double height;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.id
	 * 
	 * @return the value of xt_person.id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.id
	 * 
	 * @param id
	 *            the value for xt_person.id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.user_id
	 * 
	 * @return the value of xt_person.user_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.user_id
	 * 
	 * @param userId
	 *            the value for xt_person.user_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setUserId(long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.name
	 * 
	 * @return the value of xt_person.name
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.name
	 * 
	 * @param name
	 *            the value for xt_person.name
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.age
	 * 
	 * @return the value of xt_person.age
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.age
	 * 
	 * @param age
	 *            the value for xt_person.age
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setAge(int age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.sex
	 * 
	 * @return the value of xt_person.sex
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.sex
	 * 
	 * @param sex
	 *            the value for xt_person.sex
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setSex(int sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.birthdate
	 * 
	 * @return the value of xt_person.birthdate
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.birthdate
	 * 
	 * @param birthdate
	 *            the value for xt_person.birthdate
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.marry
	 * 
	 * @return the value of xt_person.marry
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getMarry() {
		return marry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.marry
	 * 
	 * @param marry
	 *            the value for xt_person.marry
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setMarry(int marry) {
		this.marry = marry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.nation
	 * 
	 * @return the value of xt_person.nation
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getNation() {
		return nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.nation
	 * 
	 * @param nation
	 *            the value for xt_person.nation
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setNation(String nation) {
		this.nation = nation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.birth_place
	 * 
	 * @return the value of xt_person.birth_place
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getBirthPlace() {
		return birthPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.birth_place
	 * 
	 * @param birthPlace
	 *            the value for xt_person.birth_place
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.province_code
	 * 
	 * @return the value of xt_person.province_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getProvinceCode() {
		return provinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.province_code
	 * 
	 * @param provinceCode
	 *            the value for xt_person.province_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setProvinceCode(int provinceCode) {
		this.provinceCode = provinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.province
	 * 
	 * @return the value of xt_person.province
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.province
	 * 
	 * @param province
	 *            the value for xt_person.province
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.city_code
	 * 
	 * @return the value of xt_person.city_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.city_code
	 * 
	 * @param cityCode
	 *            the value for xt_person.city_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setCityCode(int cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.city
	 * 
	 * @return the value of xt_person.city
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.city
	 * 
	 * @param city
	 *            the value for xt_person.city
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.county_code
	 * 
	 * @return the value of xt_person.county_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getCountyCode() {
		return countyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.county_code
	 * 
	 * @param countyCode
	 *            the value for xt_person.county_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setCountyCode(int countyCode) {
		this.countyCode = countyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.county
	 * 
	 * @return the value of xt_person.county
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.county
	 * 
	 * @param county
	 *            the value for xt_person.county
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setCounty(String county) {
		this.county = county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.road_code
	 * 
	 * @return the value of xt_person.road_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getRoadCode() {
		return roadCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.road_code
	 * 
	 * @param roadCode
	 *            the value for xt_person.road_code
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setRoadCode(int roadCode) {
		this.roadCode = roadCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.road
	 * 
	 * @return the value of xt_person.road
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getRoad() {
		return road;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.road
	 * 
	 * @param road
	 *            the value for xt_person.road
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setRoad(String road) {
		this.road = road;
	}

	public long getAddressId() {
		return addressId;
	}

	public void setAddressId(long addressId) {
		this.addressId = addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.home_address
	 * 
	 * @return the value of xt_person.home_address
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getHomeAddress() {
		return homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.home_address
	 * 
	 * @param homeAddress
	 *            the value for xt_person.home_address
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.occupation_id
	 * 
	 * @return the value of xt_person.occupation_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getOccupationId() {
		return occupationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.occupation_id
	 * 
	 * @param occupationId
	 *            the value for xt_person.occupation_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setOccupationId(int occupationId) {
		this.occupationId = occupationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.home_tel
	 * 
	 * @return the value of xt_person.home_tel
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getHomeTel() {
		return homeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.home_tel
	 * 
	 * @param homeTel
	 *            the value for xt_person.home_tel
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setHomeTel(String homeTel) {
		this.homeTel = homeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.social_id_type
	 * 
	 * @return the value of xt_person.social_id_type
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public int getSocialIdType() {
		return socialIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.social_id_type
	 * 
	 * @param socialIdType
	 *            the value for xt_person.social_id_type
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setSocialIdType(int socialIdType) {
		this.socialIdType = socialIdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.social_id
	 * 
	 * @return the value of xt_person.social_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getSocialId() {
		return socialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.social_id
	 * 
	 * @param socialId
	 *            the value for xt_person.social_id
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setSocialId(String socialId) {
		this.socialId = socialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.allergic_history
	 * 
	 * @return the value of xt_person.allergic_history
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public String getAllergicHistory() {
		return allergicHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.allergic_history
	 * 
	 * @param allergicHistory
	 *            the value for xt_person.allergic_history
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setAllergicHistory(String allergicHistory) {
		this.allergicHistory = allergicHistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.weight
	 * 
	 * @return the value of xt_person.weight
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public double getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.weight
	 * 
	 * @param weight
	 *            the value for xt_person.weight
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setWeight(double weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_person.height
	 * 
	 * @return the value of xt_person.height
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public double getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_person.height
	 * 
	 * @param height
	 *            the value for xt_person.height
	 * 
	 * @mbggenerated Mon Jan 18 11:40:03 CST 2016
	 */
	public void setHeight(double height) {
		this.height = height;
	}
}