package com.huatuo.pms.bo;

import java.io.Serializable;

@SuppressWarnings("serial")
public class BOUser implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.id
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.user_name
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.pwd
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private String pwd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.name
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.sex
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private int sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.mobile
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.email
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.user_type
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private String userType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.org_id
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private int orgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column xt_user.state
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	private int state;
	
	
	private String captcha;
	
	private String tureName;

	public String getCaptcha() {
		return captcha;
	}

	public void setCaptcha(String captcha) {
		this.captcha = captcha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.id
	 * 
	 * @return the value of xt_user.id
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.id
	 * 
	 * @param id
	 *            the value for xt_user.id
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.user_name
	 * 
	 * @return the value of xt_user.user_name
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.user_name
	 * 
	 * @param userName
	 *            the value for xt_user.user_name
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.pwd
	 * 
	 * @return the value of xt_user.pwd
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.pwd
	 * 
	 * @param pwd
	 *            the value for xt_user.pwd
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.name
	 * 
	 * @return the value of xt_user.name
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.name
	 * 
	 * @param name
	 *            the value for xt_user.name
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.sex
	 * 
	 * @return the value of xt_user.sex
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public int getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.sex
	 * 
	 * @param sex
	 *            the value for xt_user.sex
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setSex(int sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.mobile
	 * 
	 * @return the value of xt_user.mobile
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.mobile
	 * 
	 * @param mobile
	 *            the value for xt_user.mobile
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.email
	 * 
	 * @return the value of xt_user.email
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.email
	 * 
	 * @param email
	 *            the value for xt_user.email
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.user_type
	 * 
	 * @return the value of xt_user.user_type
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.user_type
	 * 
	 * @param userType
	 *            the value for xt_user.user_type
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.org_id
	 * 
	 * @return the value of xt_user.org_id
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public int getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.org_id
	 * 
	 * @param orgId
	 *            the value for xt_user.org_id
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setOrgId(int orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column xt_user.state
	 * 
	 * @return the value of xt_user.state
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public int getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column xt_user.state
	 * 
	 * @param state
	 *            the value for xt_user.state
	 * 
	 * @mbggenerated Tue Aug 18 12:19:49 CST 2015
	 */
	public void setState(int state) {
		this.state = state;
	}

	public String getTureName() {
		return tureName;
	}

	public void setTureName(String tureName) {
		this.tureName = tureName;
	}
}
