package com.huatuo.request;

public class FamilyForm {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private long fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.user_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.name
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.age
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.sex
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private int sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.birthdate
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.marry
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private int marry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.email
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.nation
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.birth_place
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String birthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.home_district
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.address
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.occupation_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private int occupationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.mobile
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.home_tel
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String homeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.social_id_type
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private int socialIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.social_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String socialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.allergic_history
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private String allergicHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.relation_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private int relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_person_family.related_user_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    private long relatedUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.id
     *
     * @return the value of xt_person_family.id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    
    private int provinceCode;
    
	private String province;
	
	private int cityCode;
	
	private String city;
	
	private int countyCode;
	
	private String county;
	
	private int roadCode;
	
	private String road;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.user_id
     *
     * @return the value of xt_person_family.user_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public long getUserId() {
        return userId;
    }

    

	public long getfId() {
		return fId;
	}



	public void setfId(long fId) {
		this.fId = fId;
	}



	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.user_id
     *
     * @param userId the value for xt_person_family.user_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.name
     *
     * @return the value of xt_person_family.name
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.name
     *
     * @param name the value for xt_person_family.name
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.age
     *
     * @return the value of xt_person_family.age
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.age
     *
     * @param age the value for xt_person_family.age
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.sex
     *
     * @return the value of xt_person_family.sex
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.birthdate
     *
     * @return the value of xt_person_family.birthdate
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getBirthdate() {
        return birthdate;
    }

    public int getSex() {
		return sex;
	}



	public void setSex(int sex) {
		this.sex = sex;
	}



	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.birthdate
     *
     * @param birthdate the value for xt_person_family.birthdate
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.marry
     *
     * @return the value of xt_person_family.marry
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public int getMarry() {
        return marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.marry
     *
     * @param marry the value for xt_person_family.marry
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setMarry(int marry) {
        this.marry = marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.email
     *
     * @return the value of xt_person_family.email
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.email
     *
     * @param email the value for xt_person_family.email
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.nation
     *
     * @return the value of xt_person_family.nation
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.nation
     *
     * @param nation the value for xt_person_family.nation
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.birth_place
     *
     * @return the value of xt_person_family.birth_place
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.birth_place
     *
     * @param birthPlace the value for xt_person_family.birth_place
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    public long getAddressId() {
		return addressId;
	}

	public void setAddressId(long addressId) {
		this.addressId = addressId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.address
     *
     * @return the value of xt_person_family.address
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.address
     *
     * @param address the value for xt_person_family.address
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.occupation_id
     *
     * @return the value of xt_person_family.occupation_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public int getOccupationId() {
        return occupationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.occupation_id
     *
     * @param occupationId the value for xt_person_family.occupation_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setOccupationId(int occupationId) {
        this.occupationId = occupationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.mobile
     *
     * @return the value of xt_person_family.mobile
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.mobile
     *
     * @param mobile the value for xt_person_family.mobile
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.home_tel
     *
     * @return the value of xt_person_family.home_tel
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getHomeTel() {
        return homeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.home_tel
     *
     * @param homeTel the value for xt_person_family.home_tel
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.social_id_type
     *
     * @return the value of xt_person_family.social_id_type
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public int getSocialIdType() {
        return socialIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.social_id_type
     *
     * @param socialIdType the value for xt_person_family.social_id_type
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setSocialIdType(int socialIdType) {
        this.socialIdType = socialIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.social_id
     *
     * @return the value of xt_person_family.social_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getSocialId() {
        return socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.social_id
     *
     * @param socialId the value for xt_person_family.social_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setSocialId(String socialId) {
        this.socialId = socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.allergic_history
     *
     * @return the value of xt_person_family.allergic_history
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public String getAllergicHistory() {
        return allergicHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.allergic_history
     *
     * @param allergicHistory the value for xt_person_family.allergic_history
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setAllergicHistory(String allergicHistory) {
        this.allergicHistory = allergicHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.relation_id
     *
     * @return the value of xt_person_family.relation_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public int getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.relation_id
     *
     * @param relationId the value for xt_person_family.relation_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setRelationId(int relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_person_family.related_user_id
     *
     * @return the value of xt_person_family.related_user_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public long getRelatedUserId() {
        return relatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_person_family.related_user_id
     *
     * @param relatedUserId the value for xt_person_family.related_user_id
     *
     * @mbggenerated Sat Aug 01 15:49:45 CST 2015
     */
    public void setRelatedUserId(long relatedUserId) {
        this.relatedUserId = relatedUserId;
    }


	public int getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(int provinceCode) {
		this.provinceCode = provinceCode;
	}



	public String getProvince() {
		return province;
	}



	public void setProvince(String province) {
		this.province = province;
	}



	public int getCityCode() {
		return cityCode;
	}



	public void setCityCode(int cityCode) {
		this.cityCode = cityCode;
	}



	public String getCity() {
		return city;
	}



	public void setCity(String city) {
		this.city = city;
	}



	public int getCountyCode() {
		return countyCode;
	}



	public void setCountyCode(int countyCode) {
		this.countyCode = countyCode;
	}



	public String getCounty() {
		return county;
	}



	public void setCounty(String county) {
		this.county = county;
	}



	public int getRoadCode() {
		return roadCode;
	}



	public void setRoadCode(int roadCode) {
		this.roadCode = roadCode;
	}



	public String getRoad() {
		return road;
	}



	public void setRoad(String road) {
		this.road = road;
	}

}