package com.huatuo.request;

import javax.validation.constraints.Min;

import com.huatuo.common.BeansMessage;

/** 
 * @author 作者叶林森
 * @version 创建时间：2015-8-5 上午10:52:53 
 * 类说明 
 */
public class OrgForm {
	 private long patientId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.name
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String name;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.name_py
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String namePy;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.sex
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private int sex;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.birth_date
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String birthDate;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.marry
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private int marry;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.birth_place
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String birthPlace;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.nation
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String nation;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.home_town
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private int addressId;
	    
	    private int provinceCode;
	    
		private String province;
		
		private int cityCode;
		
		private String city;
		
		private int countyCode;
		
		private String county;
		
		private int roadCode;
		
		private String road;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.home_address
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String homeAddress;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.occupation_id
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private int occupationId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.relate_tel
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String relateTel;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.social_id_type
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private int socialIdType;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.social_id
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String socialId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.doctor_id
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.operator
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String operator;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.country
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String country;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.allergic_history
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private String allergicHistory;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_patient.weight
	     *
	     * @mbggenerated Mon Aug 03 10:31:07 CST 2015
	     */
	    private double weight;

	    
	    
	    private long id;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.mz_code
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private String mzCode;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.user_id
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private long userId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.member_id
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private long memberId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.self_flag
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private int selfFlag;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.patient_id
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.times
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private int times;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.visit_time
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private String visitTime;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.start_time
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private String startTime;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.doctor_id
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    @Min(value = BeansMessage.IDVALUE, message = BeansMessage.DOCTORID)
	    private long doctorId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.end_time
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private String endTime;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.service_cost
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private double serviceCost;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.status
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private int status;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.VISIT_DEPT
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private String visitDept;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column mz_visit.AGE
	     *
	     * @mbggenerated Wed Jul 29 12:22:05 CST 2015
	     */
	    private String age;
	    
		/**
		 * 病情描述
		 */
		private String illnessDescribe;

		 

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getNamePy() {
			return namePy;
		}

		public void setNamePy(String namePy) {
			this.namePy = namePy;
		}

		public int getSex() {
			return sex;
		}

		public void setSex(int sex) {
			this.sex = sex;
		}

		public String getBirthDate() {
			return birthDate;
		}

		public void setBirthDate(String birthDate) {
			this.birthDate = birthDate;
		}

		public int getMarry() {
			return marry;
		}

		public void setMarry(int marry) {
			this.marry = marry;
		}

		public String getBirthPlace() {
			return birthPlace;
		}

		public void setBirthPlace(String birthPlace) {
			this.birthPlace = birthPlace;
		}

		public String getNation() {
			return nation;
		}

		public void setNation(String nation) {
			this.nation = nation;
		}

		public int getAddressId() {
			return addressId;
		}

		public void setAddressId(int addressId) {
			this.addressId = addressId;
		}

		public String getHomeAddress() {
			return homeAddress;
		}

		public void setHomeAddress(String homeAddress) {
			this.homeAddress = homeAddress;
		}

		public int getOccupationId() {
			return occupationId;
		}

		public void setOccupationId(int occupationId) {
			this.occupationId = occupationId;
		}

		public String getRelateTel() {
			return relateTel;
		}

		public void setRelateTel(String relateTel) {
			this.relateTel = relateTel;
		}

		public int getSocialIdType() {
			return socialIdType;
		}

		public void setSocialIdType(int socialIdType) {
			this.socialIdType = socialIdType;
		}

		public String getSocialId() {
			return socialId;
		}

		public void setSocialId(String socialId) {
			this.socialId = socialId;
		}

	 

		public String getOperator() {
			return operator;
		}

		public void setOperator(String operator) {
			this.operator = operator;
		}

		public String getCountry() {
			return country;
		}

		public void setCountry(String country) {
			this.country = country;
		}

		public String getAllergicHistory() {
			return allergicHistory;
		}

		public void setAllergicHistory(String allergicHistory) {
			this.allergicHistory = allergicHistory;
		}

		public double getWeight() {
			return weight;
		}

		public void setWeight(double weight) {
			this.weight = weight;
		}

		public long getId() {
			return id;
		}

		public void setId(long id) {
			this.id = id;
		}

		public String getMzCode() {
			return mzCode;
		}

		public void setMzCode(String mzCode) {
			this.mzCode = mzCode;
		}

		public long getUserId() {
			return userId;
		}

		public void setUserId(long userId) {
			this.userId = userId;
		}

		public long getMemberId() {
			return memberId;
		}

		public void setMemberId(long memberId) {
			this.memberId = memberId;
		}

		public int getSelfFlag() {
			return selfFlag;
		}

		public void setSelfFlag(int selfFlag) {
			this.selfFlag = selfFlag;
		}

		public long getPatientId() {
			return patientId;
		}

		public void setPatientId(long patientId) {
			this.patientId = patientId;
		}

		public int getTimes() {
			return times;
		}

		public void setTimes(int times) {
			this.times = times;
		}

		public String getVisitTime() {
			return visitTime;
		}

		public void setVisitTime(String visitTime) {
			this.visitTime = visitTime;
		}

		public String getStartTime() {
			return startTime;
		}

		public void setStartTime(String startTime) {
			this.startTime = startTime;
		}

		public long getDoctorId() {
			return doctorId;
		}

		public void setDoctorId(long doctorId) {
			this.doctorId = doctorId;
		}

		public String getEndTime() {
			return endTime;
		}

		public void setEndTime(String endTime) {
			this.endTime = endTime;
		}

		public double getServiceCost() {
			return serviceCost;
		}

		public void setServiceCost(double serviceCost) {
			this.serviceCost = serviceCost;
		}

		public int getStatus() {
			return status;
		}

		public void setStatus(int status) {
			this.status = status;
		}

		public String getVisitDept() {
			return visitDept;
		}

		public void setVisitDept(String visitDept) {
			this.visitDept = visitDept;
		}

		public String getAge() {
			return age;
		}

		public void setAge(String age) {
			this.age = age;
		}

		public int getProvinceCode() {
			return provinceCode;
		}

		public void setProvinceCode(int provinceCode) {
			this.provinceCode = provinceCode;
		}

		public String getProvince() {
			return province;
		}

		public void setProvince(String province) {
			this.province = province;
		}

		public int getCityCode() {
			return cityCode;
		}

		public void setCityCode(int cityCode) {
			this.cityCode = cityCode;
		}

		public String getCity() {
			return city;
		}

		public void setCity(String city) {
			this.city = city;
		}

		public int getCountyCode() {
			return countyCode;
		}

		public void setCountyCode(int countyCode) {
			this.countyCode = countyCode;
		}

		public String getCounty() {
			return county;
		}

		public void setCounty(String county) {
			this.county = county;
		}

		public int getRoadCode() {
			return roadCode;
		}

		public void setRoadCode(int roadCode) {
			this.roadCode = roadCode;
		}

		public String getRoad() {
			return road;
		}

		public void setRoad(String road) {
			this.road = road;
		}

		public String getIllnessDescribe() {
			return illnessDescribe;
		}

		public void setIllnessDescribe(String illnessDescribe) {
			this.illnessDescribe = illnessDescribe;
		}

}
