package com.huatuo.pms.bean;

import java.io.Serializable;


@SuppressWarnings("serial")
public class MedicalVisitBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.visit_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long visitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.patient_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.times
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.aspatient_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String aspatientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.age
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.sex
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.marry
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int marry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.nation
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.birth_place
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String birthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.home_town
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.home_address
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.occupation_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int occupationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.occupation_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String occupationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.relate_tel
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String relateTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.social_id_type
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int socialIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.social_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String socialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.create_time
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.create_doctor
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long createDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.chief_complaint
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String chiefComplaint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.allergic_history
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String allergicHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.present_illness
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String presentIllness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.past_illness
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String pastIllness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.suggestion
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String suggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.audit_doctor
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long auditDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.audit_time
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.record_status
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.body_exam
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String bodyExam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.diag_desc
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String diagDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.user_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.doctor_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private long doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.visit_status
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private int visitStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_medical_visit.doctor_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    private String doctorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.id
     *
     * @return the value of v_medical_visit.id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.id
     *
     * @param id the value for v_medical_visit.id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.visit_id
     *
     * @return the value of v_medical_visit.visit_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.visit_id
     *
     * @param visitId the value for v_medical_visit.visit_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setVisitId(long visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.patient_id
     *
     * @return the value of v_medical_visit.patient_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.patient_id
     *
     * @param patientId the value for v_medical_visit.patient_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setPatientId(long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.times
     *
     * @return the value of v_medical_visit.times
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.times
     *
     * @param times the value for v_medical_visit.times
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setTimes(int times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.aspatient_name
     *
     * @return the value of v_medical_visit.aspatient_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getAspatientName() {
        return aspatientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.aspatient_name
     *
     * @param aspatientName the value for v_medical_visit.aspatient_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setAspatientName(String aspatientName) {
        this.aspatientName = aspatientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.age
     *
     * @return the value of v_medical_visit.age
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.age
     *
     * @param age the value for v_medical_visit.age
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.sex
     *
     * @return the value of v_medical_visit.sex
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.sex
     *
     * @param sex the value for v_medical_visit.sex
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setSex(int sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.marry
     *
     * @return the value of v_medical_visit.marry
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getMarry() {
        return marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.marry
     *
     * @param marry the value for v_medical_visit.marry
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setMarry(int marry) {
        this.marry = marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.nation
     *
     * @return the value of v_medical_visit.nation
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.nation
     *
     * @param nation the value for v_medical_visit.nation
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.birth_place
     *
     * @return the value of v_medical_visit.birth_place
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.birth_place
     *
     * @param birthPlace the value for v_medical_visit.birth_place
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    public long getAddressId() {
		return addressId;
	}

	public void setAddressId(long addressId) {
		this.addressId = addressId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.home_address
     *
     * @return the value of v_medical_visit.home_address
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.home_address
     *
     * @param homeAddress the value for v_medical_visit.home_address
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.occupation_id
     *
     * @return the value of v_medical_visit.occupation_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getOccupationId() {
        return occupationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.occupation_id
     *
     * @param occupationId the value for v_medical_visit.occupation_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setOccupationId(int occupationId) {
        this.occupationId = occupationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.occupation_name
     *
     * @return the value of v_medical_visit.occupation_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getOccupationName() {
        return occupationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.occupation_name
     *
     * @param occupationName the value for v_medical_visit.occupation_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setOccupationName(String occupationName) {
        this.occupationName = occupationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.relate_tel
     *
     * @return the value of v_medical_visit.relate_tel
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getRelateTel() {
        return relateTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.relate_tel
     *
     * @param relateTel the value for v_medical_visit.relate_tel
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setRelateTel(String relateTel) {
        this.relateTel = relateTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.social_id_type
     *
     * @return the value of v_medical_visit.social_id_type
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getSocialIdType() {
        return socialIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.social_id_type
     *
     * @param socialIdType the value for v_medical_visit.social_id_type
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setSocialIdType(int socialIdType) {
        this.socialIdType = socialIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.social_id
     *
     * @return the value of v_medical_visit.social_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getSocialId() {
        return socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.social_id
     *
     * @param socialId the value for v_medical_visit.social_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setSocialId(String socialId) {
        this.socialId = socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.create_time
     *
     * @return the value of v_medical_visit.create_time
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.create_time
     *
     * @param createTime the value for v_medical_visit.create_time
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.create_doctor
     *
     * @return the value of v_medical_visit.create_doctor
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getCreateDoctor() {
        return createDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.create_doctor
     *
     * @param createDoctor the value for v_medical_visit.create_doctor
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setCreateDoctor(long createDoctor) {
        this.createDoctor = createDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.chief_complaint
     *
     * @return the value of v_medical_visit.chief_complaint
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getChiefComplaint() {
        return chiefComplaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.chief_complaint
     *
     * @param chiefComplaint the value for v_medical_visit.chief_complaint
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setChiefComplaint(String chiefComplaint) {
        this.chiefComplaint = chiefComplaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.allergic_history
     *
     * @return the value of v_medical_visit.allergic_history
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getAllergicHistory() {
        return allergicHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.allergic_history
     *
     * @param allergicHistory the value for v_medical_visit.allergic_history
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setAllergicHistory(String allergicHistory) {
        this.allergicHistory = allergicHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.present_illness
     *
     * @return the value of v_medical_visit.present_illness
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getPresentIllness() {
        return presentIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.present_illness
     *
     * @param presentIllness the value for v_medical_visit.present_illness
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setPresentIllness(String presentIllness) {
        this.presentIllness = presentIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.past_illness
     *
     * @return the value of v_medical_visit.past_illness
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getPastIllness() {
        return pastIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.past_illness
     *
     * @param pastIllness the value for v_medical_visit.past_illness
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setPastIllness(String pastIllness) {
        this.pastIllness = pastIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.suggestion
     *
     * @return the value of v_medical_visit.suggestion
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getSuggestion() {
        return suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.suggestion
     *
     * @param suggestion the value for v_medical_visit.suggestion
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.audit_doctor
     *
     * @return the value of v_medical_visit.audit_doctor
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getAuditDoctor() {
        return auditDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.audit_doctor
     *
     * @param auditDoctor the value for v_medical_visit.audit_doctor
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setAuditDoctor(long auditDoctor) {
        this.auditDoctor = auditDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.audit_time
     *
     * @return the value of v_medical_visit.audit_time
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.audit_time
     *
     * @param auditTime the value for v_medical_visit.audit_time
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setAuditTime(String auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.record_status
     *
     * @return the value of v_medical_visit.record_status
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.record_status
     *
     * @param recordStatus the value for v_medical_visit.record_status
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setRecordStatus(int recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.body_exam
     *
     * @return the value of v_medical_visit.body_exam
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getBodyExam() {
        return bodyExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.body_exam
     *
     * @param bodyExam the value for v_medical_visit.body_exam
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setBodyExam(String bodyExam) {
        this.bodyExam = bodyExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.diag_desc
     *
     * @return the value of v_medical_visit.diag_desc
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getDiagDesc() {
        return diagDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.diag_desc
     *
     * @param diagDesc the value for v_medical_visit.diag_desc
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setDiagDesc(String diagDesc) {
        this.diagDesc = diagDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.user_id
     *
     * @return the value of v_medical_visit.user_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.user_id
     *
     * @param userId the value for v_medical_visit.user_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.doctor_id
     *
     * @return the value of v_medical_visit.doctor_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.doctor_id
     *
     * @param doctorId the value for v_medical_visit.doctor_id
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setDoctorId(long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.visit_status
     *
     * @return the value of v_medical_visit.visit_status
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public int getVisitStatus() {
        return visitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.visit_status
     *
     * @param visitStatus the value for v_medical_visit.visit_status
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setVisitStatus(int visitStatus) {
        this.visitStatus = visitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_medical_visit.doctor_name
     *
     * @return the value of v_medical_visit.doctor_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_medical_visit.doctor_name
     *
     * @param doctorName the value for v_medical_visit.doctor_name
     *
     * @mbggenerated Thu Aug 27 14:08:41 CST 2015
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }
}