package com.huatuo.pms.bean;

import java.io.Serializable;

@SuppressWarnings("serial")
public class OrderDtlSupplyFrequencyBean implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_order_dtl_supply_frequency.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private long id;

    /**
     * 处方id
     */
    private long orderId;

    /**
     * 组号，默认0
     */
    private int groupId;

    /**
     * 父标记，默认0
     */
    private int isParent;

    /**
     * 药品ID
     */
    private long drugId;

    /**
     * 药品名
     */
    private String drugName;

    /**
     * 药品类型
     */
    private int drugType;

    /**
     * 规格
     */
    private String specification;

    /**
     * 剂量
     */
    private double doseOnce;

    /**
     * 剂量单位
     */
    private int doseUnit;

    /**
     * 剂量名称
     */
    private String doseName;

    /**
     * 单次用量
     */
    private double useOnce;

    /**
     * 最小单位
     */
    private int useUnit;

    /**
     * 用量名称
     */
    private String useName;

    /**
     * 购买数量
     */
    private double amount;

    /**
     * 购买单位
     */
    private int amountUnit;

    /**
     * 购买名称
     */
    private String amountName;

    /**
     * 单价
     */
    private double price;

    /**
     * 开处方的医生
     */
    private long orderDoctor;

    /**
     * 处方时间，如2015-01-01 23:59:599
     */
    private String orderTime;

    /**
     * 审核医生
     */
    private long confirmDoctor;

    /**
     * 审核时间
     */
    private String confirmTime;

    /**
     * 天数
     */
    private int days;

    /**
     * 嘱托
     */
    private String orderExplain;

    /**
     * 给药方式id
     */
    private int supplyId;

    /**
     * 给药方式
     */
    private String supplyName;

    /**
     * 服药频率id
     */
    private int frequId;

    /**
     * 频率名称
     */
    private String frequName;

    /**
     * 厂家标识
     */
    private String firmId;

    /**
     * 项目序号
     */
    private int itemNo;
    
    /**
     * 频率名称 打印短名
     */
    private String printName;

    public String getPrintName() {
		return printName;
	}

	public void setPrintName(String printName) {
		this.printName = printName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.id
     *
     * @return the value of v_order_dtl_supply_frequency.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.id
     *
     * @param id the value for v_order_dtl_supply_frequency.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.order_id
     *
     * @return the value of v_order_dtl_supply_frequency.order_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.order_id
     *
     * @param orderId the value for v_order_dtl_supply_frequency.order_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.group_id
     *
     * @return the value of v_order_dtl_supply_frequency.group_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.group_id
     *
     * @param groupId the value for v_order_dtl_supply_frequency.group_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.is_parent
     *
     * @return the value of v_order_dtl_supply_frequency.is_parent
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.is_parent
     *
     * @param isParent the value for v_order_dtl_supply_frequency.is_parent
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setIsParent(int isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.drug_id
     *
     * @return the value of v_order_dtl_supply_frequency.drug_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.drug_id
     *
     * @param drugId the value for v_order_dtl_supply_frequency.drug_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDrugId(long drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.drug_name
     *
     * @return the value of v_order_dtl_supply_frequency.drug_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.drug_name
     *
     * @param drugName the value for v_order_dtl_supply_frequency.drug_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.drug_type
     *
     * @return the value of v_order_dtl_supply_frequency.drug_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getDrugType() {
        return drugType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.drug_type
     *
     * @param drugType the value for v_order_dtl_supply_frequency.drug_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDrugType(int drugType) {
        this.drugType = drugType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.specification
     *
     * @return the value of v_order_dtl_supply_frequency.specification
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.specification
     *
     * @param specification the value for v_order_dtl_supply_frequency.specification
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setSpecification(String specification) {
        this.specification = specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.dose_once
     *
     * @return the value of v_order_dtl_supply_frequency.dose_once
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public double getDoseOnce() {
        return doseOnce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.dose_once
     *
     * @param doseOnce the value for v_order_dtl_supply_frequency.dose_once
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDoseOnce(double doseOnce) {
        this.doseOnce = doseOnce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.dose_unit
     *
     * @return the value of v_order_dtl_supply_frequency.dose_unit
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getDoseUnit() {
        return doseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.dose_unit
     *
     * @param doseUnit the value for v_order_dtl_supply_frequency.dose_unit
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDoseUnit(int doseUnit) {
        this.doseUnit = doseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.dose_name
     *
     * @return the value of v_order_dtl_supply_frequency.dose_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getDoseName() {
        return doseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.dose_name
     *
     * @param doseName the value for v_order_dtl_supply_frequency.dose_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDoseName(String doseName) {
        this.doseName = doseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.use_once
     *
     * @return the value of v_order_dtl_supply_frequency.use_once
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public double getUseOnce() {
        return useOnce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.use_once
     *
     * @param useOnce the value for v_order_dtl_supply_frequency.use_once
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setUseOnce(double useOnce) {
        this.useOnce = useOnce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.use_unit
     *
     * @return the value of v_order_dtl_supply_frequency.use_unit
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getUseUnit() {
        return useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.use_unit
     *
     * @param useUnit the value for v_order_dtl_supply_frequency.use_unit
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setUseUnit(int useUnit) {
        this.useUnit = useUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.use_name
     *
     * @return the value of v_order_dtl_supply_frequency.use_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getUseName() {
        return useName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.use_name
     *
     * @param useName the value for v_order_dtl_supply_frequency.use_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setUseName(String useName) {
        this.useName = useName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.amount
     *
     * @return the value of v_order_dtl_supply_frequency.amount
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.amount
     *
     * @param amount the value for v_order_dtl_supply_frequency.amount
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.amount_unit
     *
     * @return the value of v_order_dtl_supply_frequency.amount_unit
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getAmountUnit() {
        return amountUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.amount_unit
     *
     * @param amountUnit the value for v_order_dtl_supply_frequency.amount_unit
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setAmountUnit(int amountUnit) {
        this.amountUnit = amountUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.amount_name
     *
     * @return the value of v_order_dtl_supply_frequency.amount_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getAmountName() {
        return amountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.amount_name
     *
     * @param amountName the value for v_order_dtl_supply_frequency.amount_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setAmountName(String amountName) {
        this.amountName = amountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.price
     *
     * @return the value of v_order_dtl_supply_frequency.price
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.price
     *
     * @param price the value for v_order_dtl_supply_frequency.price
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.order_doctor
     *
     * @return the value of v_order_dtl_supply_frequency.order_doctor
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getOrderDoctor() {
        return orderDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.order_doctor
     *
     * @param orderDoctor the value for v_order_dtl_supply_frequency.order_doctor
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderDoctor(long orderDoctor) {
        this.orderDoctor = orderDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.order_time
     *
     * @return the value of v_order_dtl_supply_frequency.order_time
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.order_time
     *
     * @param orderTime the value for v_order_dtl_supply_frequency.order_time
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.confirm_doctor
     *
     * @return the value of v_order_dtl_supply_frequency.confirm_doctor
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getConfirmDoctor() {
        return confirmDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.confirm_doctor
     *
     * @param confirmDoctor the value for v_order_dtl_supply_frequency.confirm_doctor
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setConfirmDoctor(long confirmDoctor) {
        this.confirmDoctor = confirmDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.confirm_time
     *
     * @return the value of v_order_dtl_supply_frequency.confirm_time
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.confirm_time
     *
     * @param confirmTime the value for v_order_dtl_supply_frequency.confirm_time
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setConfirmTime(String confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.days
     *
     * @return the value of v_order_dtl_supply_frequency.days
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.days
     *
     * @param days the value for v_order_dtl_supply_frequency.days
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDays(int days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.order_explain
     *
     * @return the value of v_order_dtl_supply_frequency.order_explain
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getOrderExplain() {
        return orderExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.order_explain
     *
     * @param orderExplain the value for v_order_dtl_supply_frequency.order_explain
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderExplain(String orderExplain) {
        this.orderExplain = orderExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.supply_id
     *
     * @return the value of v_order_dtl_supply_frequency.supply_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getSupplyId() {
        return supplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.supply_id
     *
     * @param supplyId the value for v_order_dtl_supply_frequency.supply_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setSupplyId(int supplyId) {
        this.supplyId = supplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.supply_name
     *
     * @return the value of v_order_dtl_supply_frequency.supply_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getSupplyName() {
        return supplyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.supply_name
     *
     * @param supplyName the value for v_order_dtl_supply_frequency.supply_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setSupplyName(String supplyName) {
        this.supplyName = supplyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.frequ_id
     *
     * @return the value of v_order_dtl_supply_frequency.frequ_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getFrequId() {
        return frequId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.frequ_id
     *
     * @param frequId the value for v_order_dtl_supply_frequency.frequ_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setFrequId(int frequId) {
        this.frequId = frequId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.frequ_name
     *
     * @return the value of v_order_dtl_supply_frequency.frequ_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getFrequName() {
        return frequName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.frequ_name
     *
     * @param frequName the value for v_order_dtl_supply_frequency.frequ_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setFrequName(String frequName) {
        this.frequName = frequName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.FIRM_ID
     *
     * @return the value of v_order_dtl_supply_frequency.FIRM_ID
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getFirmId() {
        return firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.FIRM_ID
     *
     * @param firmId the value for v_order_dtl_supply_frequency.FIRM_ID
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setFirmId(String firmId) {
        this.firmId = firmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_order_dtl_supply_frequency.ITEM_NO
     *
     * @return the value of v_order_dtl_supply_frequency.ITEM_NO
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_order_dtl_supply_frequency.ITEM_NO
     *
     * @param itemNo the value for v_order_dtl_supply_frequency.ITEM_NO
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setItemNo(int itemNo) {
        this.itemNo = itemNo;
    }
}