package com.huatuo.pms.bean;

import java.io.Serializable;
import java.math.BigDecimal;

@SuppressWarnings("serial")
public class OrderBean implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_order.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private long id;

    /**
     * 就诊记录id
     */
    private long visitId;

    /**
     * 处方类型( 1:西药处方 2:中草药处方)
     */
    private int orderType;

    /**
     * 剂数
     */
    private int amount;

    /**
     * 处方说明
     */
    private String orderExplain;

    /**
     * 处方号
     */
    private String orderNo;

    /**
     * 单价
     */
    private BigDecimal price;

    /**
     * 删除标记，0正常，1删除
     */
    private boolean delFlag;
    
    /**
     * 审核状态(0:未审核,1:审核,2:驳回,3:超时通过,4:未提交)
     */
    private int taskState;

    /**
     * 审核人用户id
     */
    private long taskUid;
    
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.id
     *
     * @param id the value for mz_order.id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_order.visit_id
     *
     * @return the value of mz_order.visit_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getVisitId() {
        return visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.visit_id
     *
     * @param visitId the value for mz_order.visit_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setVisitId(long visitId) {
        this.visitId = visitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_order.order_type
     *
     * @return the value of mz_order.order_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.order_type
     *
     * @param orderType the value for mz_order.order_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderType(int orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_order.amount
     *
     * @return the value of mz_order.amount
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.amount
     *
     * @param amount the value for mz_order.amount
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_order.order_explain
     *
     * @return the value of mz_order.order_explain
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getOrderExplain() {
        return orderExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.order_explain
     *
     * @param orderExplain the value for mz_order.order_explain
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderExplain(String orderExplain) {
        this.orderExplain = orderExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_order.order_no
     *
     * @return the value of mz_order.order_no
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.order_no
     *
     * @param orderNo the value for mz_order.order_no
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }



    public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_order.del_flag
     *
     * @return the value of mz_order.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public boolean isDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_order.del_flag
     *
     * @param delFlag the value for mz_order.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDelFlag(boolean delFlag) {
        this.delFlag = delFlag;
    }

	public int getTaskState() {
		return taskState;
	}

	public void setTaskState(int taskState) {
		this.taskState = taskState;
	}

	public long getTaskUid() {
		return taskUid;
	}

	public void setTaskUid(long taskUid) {
		this.taskUid = taskUid;
	}
	
}