package com.huatuo.pms.bean;

import java.io.Serializable;

public class OrgDetailBean implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -5885643549379390076L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.user_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.org_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.parent_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.alias_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String aliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.user_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.org_kind
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int orgKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.org_district
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int orgDistrict;
    
    private int provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.province
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.city_code
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private int cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.city
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.county_code
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private int countyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.county
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.road_code
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private int roadCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zd_org.road
     *
     * @mbggenerated Mon Jan 18 11:32:37 CST 2016
     */
    private String road;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.address
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.setup_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int setupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.scale
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.telephone
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.py_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String pyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.email
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.description
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.d_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private String dCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.state
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private int state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org_detail.open_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    private boolean openFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.user_id
     *
     * @return the value of v_org_detail.user_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.user_id
     *
     * @param userId the value for v_org_detail.user_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.org_id
     *
     * @return the value of v_org_detail.org_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.org_id
     *
     * @param orgId the value for v_org_detail.org_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrgId(int orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.parent_id
     *
     * @return the value of v_org_detail.parent_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.parent_id
     *
     * @param parentId the value for v_org_detail.parent_id
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setParentId(int parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.name
     *
     * @return the value of v_org_detail.name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.name
     *
     * @param name the value for v_org_detail.name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.alias_name
     *
     * @return the value of v_org_detail.alias_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.alias_name
     *
     * @param aliasName the value for v_org_detail.alias_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.user_name
     *
     * @return the value of v_org_detail.user_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.user_name
     *
     * @param userName the value for v_org_detail.user_name
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.org_kind
     *
     * @return the value of v_org_detail.org_kind
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getOrgKind() {
        return orgKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.org_kind
     *
     * @param orgKind the value for v_org_detail.org_kind
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrgKind(int orgKind) {
        this.orgKind = orgKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.org_district
     *
     * @return the value of v_org_detail.org_district
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getOrgDistrict() {
        return orgDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.org_district
     *
     * @param orgDistrict the value for v_org_detail.org_district
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOrgDistrict(int orgDistrict) {
        this.orgDistrict = orgDistrict;
    }
    
    public int getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(int provinceCode) {
		this.provinceCode = provinceCode;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public int getCityCode() {
		return cityCode;
	}

	public void setCityCode(int cityCode) {
		this.cityCode = cityCode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public int getCountyCode() {
		return countyCode;
	}

	public void setCountyCode(int countyCode) {
		this.countyCode = countyCode;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public int getRoadCode() {
		return roadCode;
	}

	public void setRoadCode(int roadCode) {
		this.roadCode = roadCode;
	}

	public String getRoad() {
		return road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.address
     *
     * @return the value of v_org_detail.address
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.address
     *
     * @param address the value for v_org_detail.address
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.setup_type
     *
     * @return the value of v_org_detail.setup_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getSetupType() {
        return setupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.setup_type
     *
     * @param setupType the value for v_org_detail.setup_type
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setSetupType(int setupType) {
        this.setupType = setupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.scale
     *
     * @return the value of v_org_detail.scale
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.scale
     *
     * @param scale the value for v_org_detail.scale
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setScale(int scale) {
        this.scale = scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.telephone
     *
     * @return the value of v_org_detail.telephone
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.telephone
     *
     * @param telephone the value for v_org_detail.telephone
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.py_code
     *
     * @return the value of v_org_detail.py_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getPyCode() {
        return pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.py_code
     *
     * @param pyCode the value for v_org_detail.py_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setPyCode(String pyCode) {
        this.pyCode = pyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.email
     *
     * @return the value of v_org_detail.email
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.email
     *
     * @param email the value for v_org_detail.email
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.description
     *
     * @return the value of v_org_detail.description
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.description
     *
     * @param description the value for v_org_detail.description
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.d_code
     *
     * @return the value of v_org_detail.d_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public String getdCode() {
        return dCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.d_code
     *
     * @param dCode the value for v_org_detail.d_code
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setdCode(String dCode) {
        this.dCode = dCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.state
     *
     * @return the value of v_org_detail.state
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public int getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.state
     *
     * @param state the value for v_org_detail.state
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setState(int state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.del_flag
     *
     * @return the value of v_org_detail.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public boolean isDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.del_flag
     *
     * @param delFlag the value for v_org_detail.del_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setDelFlag(boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org_detail.open_flag
     *
     * @return the value of v_org_detail.open_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public boolean isOpenFlag() {
        return openFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org_detail.open_flag
     *
     * @param openFlag the value for v_org_detail.open_flag
     *
     * @mbggenerated Tue Aug 18 12:19:49 CST 2015
     */
    public void setOpenFlag(boolean openFlag) {
        this.openFlag = openFlag;
    }

}